name    'lab42-wordpress'
version '2.0.0'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-wordpress'
summary 'Puppet module for wordpress'
description 'This module installs and manages wordpress. Check README for details. Puppi and monitor dependencies are needed only if the relevant features are enabled'
dependency 'puppetlabs/stdlib', '>= 0.1.0'
dependency 'lab42/stdlib42', '>= 2.0.0'
dependency 'lab42/puppi', '>= 2.0.0'
dependency 'lab42/monitor', '>= 2.0.0'
