name 'example42-wordpress'
version '2.0.7'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-wordpress'
summary 'Puppet module for wordpress'
description 'This module installs and manages wordpress. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/apache', '>=2.0.0'
dependency 'example42/php', '>=2.0.0'
dependency 'example42/mysql', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
dependency 'example42/nginx', '>=2.0.0'
